### ISSUE TITLE
Unsupported operand types: array & int

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/myalbum#5]
When I go on user side I get this error:

Error: TypeError: Unsupported operand types: array & int in file /modules/myalbum/index.php line 66

___

My config

MyAlbum 3.09 Beta 1 (english version)
Xoops 2.5.11-Beta2 (english version)
PHP 8.1.2
MYSQL 8.0.30-0ubuntu0.22.04.1

**Comment by cesagonchu** [comment]
I don't have this problem anymore with the new version MyAlbum 3.09 beta 3

**Comment by mambax7** [comment]
Thank you for letting me know.
