### ISSUE TITLE
Unknown: trim(): Passing null to parameter #1 ($string)

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/myalbum#7]
When I go to "Dashboard" tab I get this error:

Unknown: trim(): Passing null to parameter #1 ($string) of type string is deprecated in file /class/libraries/vendor/symfony/yaml/Inline.php line 49

___
My config

MyAlbum 3.09 Beta 1 (english version)
Xoops 2.5.11-Beta2 (english version)
PHP 8.1.2
MYSQL 8.0.30-0ubuntu0.22.04.1

**Comment by mambax7** [comment]
You can ignore all "deprecated" notices - they are just warnings for developers. 
In this case, it is because we keep XOOPS compatibility with PHP 5.3.9, and this requires an older version of Symfony YAML. 
For the time being, you can ignore this issue, otherwise, you can change the line 49 to:

```php
$value = trim($value??'');
```
