### ISSUE TITLE
TextHandler

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/myalbum#8]
After installing the module and when I go on admin side I get this error:

Error: TypeError: XoopsModules/Myalbum/TextHandler::getBytes(): Return value must be of type string, null returned in file /modules/myalbum/class/TextHandler.php line 40

___
My config

MyAlbum 3.09 Beta 3 (english version)
Xoops 2.5.11-Beta2 (english version)
PHP 8.1.2
MYSQL 8.0.30-0ubuntu0.22.04.1

**Comment by mambax7** [comment]
Should be fixed now
