### ISSUE TITLE
error on help tab

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/myalbum#9]
When I go to the "help" tab on the administration side (/modules/system/help.php?mid=5&page=help), I get this error:

Error: Undefined constant "_MI_MYALBUM_HELP_HEADER" in file /xoops_dataxxxx/caches/smarty_compile/f9c52d55-system-cp-transition-default^%%CB^CB8^CB827233%%help.tpl.php line 5

___
My config

MyAlbum 3.09 Beta 3 (english version)
Xoops 2.5.11-Beta2 (english version)
PHP 8.1.2
MYSQL 8.0.30-0ubuntu0.22.04.1

**Comment by mambax7** [comment]
Should be fixe now in https://github.com/mambax7/myalbum/commit/dda4790c6efaf5292d1917840cf1d536dfb0f966
